// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"time"
)

type OrderDetail struct {
	Oid       int64     `db:"oid"`
	UserID    int64     `db:"user_id"`
	Total     string    `db:"total"`
	PaymentID int64     `db:"payment_id"`
	CreatedAt time.Time `db:"created_at"`
	UpdatedAt time.Time `db:"updated_at"`
}

type OrderItem struct {
	Oiid      int64     `db:"oiid"`
	OrderID   int64     `db:"order_id"`
	ProductID int64     `db:"product_id"`
	CreatedAt time.Time `db:"created_at"`
	UpdatedAt time.Time `db:"updated_at"`
}

type Payment struct {
	Pid         int64     `db:"pid"`
	OrderID     int64     `db:"order_id"`
	Amount      string    `db:"amount"`
	PaymentType string    `db:"payment_type"`
	Status      string    `db:"status"`
	CreatedAt   time.Time `db:"created_at"`
	UpdatedAt   time.Time `db:"updated_at"`
}

type Product struct {
	Proid       int64     `db:"proid"`
	Name        string    `db:"name"`
	Description string    `db:"description"`
	Category    string    `db:"category"`
	Price       string    `db:"price"`
	Stock       int32     `db:"stock"`
	CreatedAt   time.Time `db:"created_at"`
	UpdatedAt   time.Time `db:"updated_at"`
}

type User struct {
	Uid       int64     `db:"uid"`
	Username  string    `db:"username"`
	Password  string    `db:"password"`
	Name      string    `db:"name"`
	Address   string    `db:"address"`
	MobileNo  string    `db:"mobile_no"`
	CreatedAt time.Time `db:"created_at"`
	UpdatedAt time.Time `db:"updated_at"`
}
